# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_page1_calib.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 296)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_folder.setStyleSheet("\n"
"background-color: rgb(243, 243, 243);")
        self.lineEdit_folder.setObjectName("lineEdit_folder")
        self.horizontalLayout.addWidget(self.lineEdit_folder)
        self.pbt_browse = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_browse.setObjectName("pbt_browse")
        self.horizontalLayout.addWidget(self.pbt_browse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_num = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_num.setMinimumSize(QtCore.QSize(120, 0))
        self.spinBox_num.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.spinBox_num.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_num.setMaximum(10000)
        self.spinBox_num.setObjectName("spinBox_num")
        self.horizontalLayout_2.addWidget(self.spinBox_num)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbt_shot = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_shot.setObjectName("pbt_shot")
        self.horizontalLayout_3.addWidget(self.pbt_shot)
        self.pbt_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_stop.setObjectName("pbt_stop")
        self.horizontalLayout_3.addWidget(self.pbt_stop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.label_image.setText("")
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.verticalLayout.addWidget(self.label_image)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CalibSnap"))
        self.label.setText(_translate("MainWindow", "Select Folder"))
        self.pbt_browse.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Image Number"))
        self.pbt_shot.setText(_translate("MainWindow", "SnapShot"))
        self.pbt_stop.setText(_translate("MainWindow", "Stop"))
import ima_rc
